Promises in Asynchronous Programming  

# 异步编程中的承诺

在前两章中，我们研究了 Node 中异步编程的许多重要概念。这一章是关于承诺的。从 ES6 开始，承诺就以 JavaScript 提供。尽管它们在第三方库中已经存在了相当长的一段时间，但它们最终进入了核心 JavaScript 语言，这非常棒，因为它们是一个非常棒的特性。

在本章中，我们将了解承诺是如何工作的，我们将开始确切地理解它们为什么有用，以及它们为什么会出现在 JavaScript 中。我们将看看一个名为 axios 的库，它支持承诺。这将使我们简化代码，轻松创建承诺调用。在最后一节中，我们将实际重建整个天气应用程序。

具体来说，我们将研究以下主题：

*   ES6 承诺简介
*   预先承诺
*   承诺天气应用程序

# ES6 承诺简介

Promissions 旨在解决应用程序中有大量异步代码时出现的许多问题。它们使我们更容易管理异步计算，例如从数据库请求数据。或者，在天气应用程序的情况下，可以从 URL 获取数据。

在`app.js`文件中，我们使用回调执行类似的操作：

```
const yargs = require('yargs');

const geocode = require('./geocode/geocode');
const weather = require('./weather/weather');

const argv = yargs
  .options({
    a: {
      demand: true,
      alias: 'address',
      describe: 'Address to fetch weather for',
      string: true
    }
  })
  .help()
  .alias('help', 'h')
  .argv;

geocode.geocodeAddress(argv.address, (errorMessage, results) => {
  if (errorMessage) {
    console.log(errorMessage);
  } else {
    console.log(results.address);
    weather.getWeather(results.latitude, results.longitude, (errorMessage, weatherResults) => {
      if (errorMessage) {
        console.log(errorMessage);
      } else {
        console.log(`It's currently ${weatherResults.temperature}. It feels like ${weatherResults.apparentTemperature}.`);
      }
    });
  }
});
```

在此代码中，我们有两个回调：

*   进入`geocodeAddress`的人
*   进入`getWeather`的人

我们使用它来管理异步操作。在我们的例子中，就是使用 HTTP 请求从 API 获取数据。在本例中，我们可以使用承诺使代码变得更好。这正是本章后面的目标。

在本节中，我们将探讨承诺的基本概念。我们将把回调和承诺进行比较和对比，因为在不确切知道承诺是如何工作的情况下，有很多微妙之处是无法描述的。所以，在我们讨论为什么它们更好之前，我们将简单地创建一些。

# 创建一个示例承诺

在 Atom 的`playground`文件夹中，我们将创建一个新文件，并将其命名为`promise.js`。在我们定义承诺并讨论其具体工作原理之前，我们将先看一个简单的示例，因为这是通过示例了解任何内容并了解其工作原理的最佳方法。

首先，我们将学习一个非常基本的示例。我们将坚持核心承诺功能。

为了开始这个非常简单的示例，我们将创建一个名为`somePromise`的变量。这将最终存储 promise 对象。我们将调用这个变量的各种方法来实现这个承诺。我们将把`somePromise`变量设置为等于承诺构造函数的返回结果。我们将使用`new`关键字创建承诺的新实例。然后，我们将提供我们想要创建一个新实例的东西，`Promise`，如下所示：

```
var somePromise = new Promise
```

现在这个`Promise`函数，它确实是一个函数，我们必须像一个函数一样调用它；也就是说，它需要一个论点。此参数将是一个函数。我们将使用一个匿名箭头函数（`=>`），在该函数中，我们将执行所有我们想要执行的异步操作：

```
var somePromise = new Promise(() => {

});
```

这一切都将被抽象，有点像我们在`geocode.js`文件中的`geocodeAddress`函数中抽象 HTTP 请求：

```
const request = require('request');

var geocodeAddress = (address, callback) => {
  var encodedAddress = encodeURIComponent(address);

  request({
    url: `https://maps.googleapis.com/maps/api/geocode/json?address=${encodedAddress}`,
    json: true
  }, (error, response, body) => {
    if (error) {
      callback('Unable to connect to Google servers.');
    } else if (body.status === 'ZERO_RESULTS') {
      callback('Unable to find that address.');
    } else if (body.status === 'OK') {
      callback(undefined, {
        address: body.results[0].formatted_address,
        latitude: body.results[0].geometry.location.lat,
        longitude: body.results[0].geometry.location.lng
      });
    }
  });
};

module.exports.geocodeAddress = geocodeAddress;
```

`geocodeAddress`函数中的所有复杂逻辑确实需要发生，但`app.js`文件不需要担心。`app.js`文件中的`geocode.geocodeAddress`函数有一个非常简单的`if`语句，用于检查是否存在错误。如果有错误，我们将打印一条消息，如果没有，我们将继续。承诺也是如此。

`new Promise`回调函数将被两个参数调用，`resolve`和`reject`：

```
var somePromise = new Promise((resolve, reject) => {

});
```

这就是我们将如何管理我们承诺的状态。当我们许下承诺时，我们就是在许下承诺；我们在说，“嘿，我去给你拿网站数据。”现在一切都会好起来，在这种情况下，你将`resolve`承诺，将其状态设置为履行。当一个承诺实现时，它就消失了，它完成了你期望它做的事情。这可能是一个数据库请求、一个 HTTP 请求或其他完全不同的请求。

现在，当你打电话给`reject`时，你是说，“嘿，我们试图完成那件事，但我们就是做不到。”所以这个承诺被认为是被拒绝了。这是两种状态，你可以设定承诺履行或拒绝。就像`geocode.js`中一样，我们要么为错误提供一个参数，要么在事情进展顺利时提供第二个参数。但是，承诺并没有这样做，而是给了我们两个可以调用的函数。

现在，为了确切地说明如何使用这些，我们将调用`resolve`。同样，这不是异步的。我们还没有做什么。所以所有这些基本上都是实时发生的，正如你们在终端中看到的。我们会打电话给`resolve`，提供一些数据。在本例中，我将传入一个字符串`Hey. It worked!`，如下所示：

```
var somePromise = new Promise((resolve, reject) => {
     resolve('Hey. It worked!');
});
```

现在，这个字符串是履行承诺的值。这正是有人会得到的。对于 app 文件中的`geocode.geocodeAddress`函数，可能是数据，无论是结果还是错误消息。但在我们的例子中，我们使用的是`resolve`，因此这将是用户想要的实际数据。当事情进展顺利时，`Hey. It worked!`就是他们所期望的。

Now you can only pass one argument to both `resolve` and `reject`, which means that if you want to provide multiple pieces of information I recommend that you resolve or reject an object that you can set multiple properties on. In our case though, a simple message, `Hey. It worked!`, will do the job.

# 然后调用 promise 方法

现在，为了在承诺得到解决或拒绝时实际执行某些操作，我们需要调用一个名为`then`的承诺方法；`somePromise.then`。`then`方法允许我们为成功和错误案例提供`callback`功能。这是回调与承诺不同的领域之一。在一个回调中，我们有一个函数，不管发生什么都会启动，参数让我们知道事情是否进展顺利。有了承诺，我们将有两个功能，这将决定事情是否按计划进行。

现在，在我们开始添加两个函数之前，让我们先从一个函数开始。在这里，我将调用，传入一个函数。只有当承诺得到履行时，才会调用此函数。这意味着它按预期工作。当它这样做时，它将被调用，并将值传递给`resolve`。在我们的例子中，它是一个简单的`message`，但在数据库请求的情况下，它可以类似于用户对象。但现在，我们将继续使用`message`：

```
somePromise.then((message) => {

})
```

这将在屏幕上打印`message`。在回调内部，当承诺实现时，我们将调用`console.log`，打印`Success`，然后作为第二个参数，我们将打印实际的`message`变量：

```
somePromise.then((message) => {
  console.log('Success: ', message);
})
```

# 在终端中运行 promise 示例

现在我们有了一个非常基本的 promise 示例，让我们使用`nodemon`从终端运行它，我们在上一章中安装了`nodemon`。我们将添加`nodemon`，然后进入`playground`文件夹`/promise.js`：

![](assets/1baa93e7-2dda-4403-af61-a5918704c603.png)

当我们立即这样做时，我们的应用程序就会运行，我们就会获得成功。`Hey. It worked!`这是瞬间发生的。没有延迟，因为我们没有异步执行任何操作。现在，当我们第一次探索回调时（参考[第 5 章](05.html)，*Node.js*中的异步编程基础），我们使用`setTimeout`来模拟延迟，这正是我们在本例中要做的。

在`somePromise`函数中，我们将调用`setTimeout`，传入两个参数：延迟后要调用的函数和以毫秒为单位的延迟。我将使用`2500`，即 2.5 秒：

```
var somePromise = new Promise((resolve, reject) => {
 setTimeout(() => {

}, 2500);
```

现在，在这 2.5 秒结束之后，然后，也只有到那时，我们才想兑现承诺。这意味着我们传递到的函数在 2.5 秒内不会被调用。因为，正如我们所知，在承诺达成之前，这不会被调用。我将保存该文件，该文件将重新启动`nodemon`：

![](assets/3b7bd22e-6649-463f-b385-3764d2b41738.png)

在终端中，您可以看到我们有延迟，然后`success: Hey it worked!`打印到屏幕上。这 2.5 秒的延迟是由`setTimeout`引起的。延迟结束后（在本例中是人为延迟，但稍后将是真正的延迟），我们能够`resolve`处理数据。

# 承诺中的错误处理

现在有可能事情进展不顺利。我们必须处理节点应用程序中的错误。在这种情况下，我们不会调用`resolve`，而是调用`reject`。让我们注释掉`resolve`行，然后创建第二行，我们称之为`reject`。我们将调用`reject`的方式与调用`resolve`的方式大致相同。我们必须传入一个参数，在这种情况下，像`Unable to fulfill promise`这样的简单错误消息可以：

```
var somePromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    // resolve('Hey. It worked!');
    reject('Unable to fulfill promise');
  }, 2500);
});
```

现在当我们打电话给`reject`时，我们告诉承诺它已经被拒绝了。这意味着我们试图做的事情进展不顺利。目前，我们没有处理这个问题的参数。正如我们提到的，这个函数只有在事情按预期进行时才被调用，而不是在出现错误时。如果我保存文件并在终端中重新运行，我们将得到一个拒绝的承诺：

![](assets/a5925ae3-0b3a-4186-8be9-73ed7d094396.png)

但是，我们没有它的处理程序，因此不会在屏幕上打印任何内容。这将是一个相当大的问题。我们需要处理那个错误消息。我们可能会提醒用户，或者尝试其他代码。

如前面的代码输出所示，我们可以看到在重新启动和退出之间没有打印任何内容。为了处理错误，我们将在`then`方法中添加第二个参数。这第二个论点让我们能够处理承诺中的错误。此参数将被执行并使用该值调用。在这种情况下，这是我们的信息。我们将创建一个名为`errorMessage`的参数，如下所示：

```
somePromise.then((message) => {
  console.log('Success: ', message);
}, (errorMessage) => {

});
```

在这场争论中，我们可以做些事情。在本例中，我们将使用`console.log`将其打印到屏幕上，使用冒号和空格打印`Error`以添加一些好的格式，后跟被拒绝的实际值：

```
}, (errorMessage) => {
  console.log('Error: ', errorMessage);
});
```

现在我们已经准备好了，我们可以通过保存文件来刷新内容。现在，我们将在终端中看到错误消息，因为我们现在有一个位置让它执行某些操作：

![](assets/6a3cb6c6-97d1-4630-8932-6e8a8bfaa198.png)

在这里，我们有一个地方让它把信息打印到屏幕上；`Unable to fulfill promise`打印到屏幕上，完全按照预期工作。

# 承诺的优点

我们现在有一个承诺，要么得到解决，要么被拒绝。如果它得到解决，意味着承诺得到了履行，我们有一个函数来处理这个问题。如果它被拒绝，我们有一个函数也可以处理它。这就是承诺令人敬畏的原因之一。根据承诺是否得到解决或拒绝，您可以提供不同的功能。这可以避免代码中出现大量复杂的`if`语句，我们需要在`app.js`中执行这些语句来管理实际回调是否成功。

现在在承诺中，重要的是要明白你只能`resolve`或`reject`一次承诺。如果你`resolve`承诺你以后不能`reject`兑现，如果你`resolve`承诺有一个价值，你就不能在以后改变主意。考虑这个例子，在这里我有一个像下面的代码一样的代码；这里我先`resolve`然后我`reject`：

```
var somePromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('Hey. It worked!');
    reject('Unable to fulfill promise');
  }, 2500);
});

somePromise.then((message) => {
  console.log('Success: ', message);
}, (errorMessage) => {
  console.log('Error: ', errorMessage);
});
```

在这种情况下，我们将成功地`message`打印到屏幕上。我们永远不会看到`errorMessage`，因为，正如我刚才所说的，你只能做其中一个动作一次。你可以`resolve`一次，也可以`reject`一次。你不能两者都做；两次都不行。

这是与回调相比的另一个巨大优势。没有什么能阻止我们意外地调用`callback`函数两次。让我们考虑一下{ To.T1A.file”。让我们在 geocode 请求调用的`if`块中添加另一行，如下所示：

```
const request = require('request');

var geocodeAddress = (address, callback) => {
  var encodedAddress = encodeURIComponent(address);

  request({
    url: `https://maps.googleapis.com/maps/api/geocode/json?address=${encodedAddress}`,
    json: true
  }, (error, response, body) => {
    if (error) {
      callback('Unable to connect to Google servers.');
      callback();
```

这是一个更明显的例子，但它很容易隐藏在复杂的`if-else`语句中。在这种情况下，`app.js`中的`callback`函数确实会被调用两次，这会给我们的程序带来很大的问题。在 promise 示例中，此回调永远不会被调用两次，无论您尝试调用`resolve`或`reject`多少次，此函数都只会被触发一次。

我们现在可以通过再次致电`resolve`来证明这一点。在 promise 示例中，让我们使用以下更改保存文件：

```
var somePromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('Hey. It worked!');
    resolve();
    reject('Unable to fulfill promise');
  }, 2500);
});
```

现在，让我们刷新一下；我们将使用我们的消息`resolve`，并且我们将永远不会在没有消息的情况下再次启动该函数。因为，正如我们所说，承诺已经解决了。一旦将承诺的状态设置为“已履行”或“已拒绝”，就不能再次设置。

现在，在调用 promise 的`resolve`或`reject`函数之前，promise 处于被称为 pending 的状态。这意味着您正在等待信息返回，或者等待异步计算完成。在我们的例子中，当我们等待天气数据回来时，这一承诺将被视为悬而未决。承诺履行或被拒绝时，视为已解决。

无论你选择哪一个，你都可以说承诺已经达成，这意味着它不再悬而未决。在我们的例子中，这将是一个已经实现的承诺，因为`resolve`就在这里被调用。所以这些只是承诺的几个好处。您不必担心回调调用两次，您可以提供多个函数，一个用于成功处理，一个用于错误处理。这真是一个了不起的实用工具！

现在，我们已经通过了一个简单的例子来说明承诺是如何起作用的，我们将回顾一下最基本的内容，接下来我们将讨论一些稍微复杂一些的内容。

# 预先承诺

在本节中，我们将探讨另外两种使用承诺的方法。我们将创建接受输入并返回承诺的函数。此外，我们还将探讨承诺链，这将使我们能够组合多个承诺。

# 为承诺提供投入

上一节讨论的示例的问题是，我们有一个 promise 函数，但它不接受任何输入。当我们使用真实世界的承诺时，这种情况很可能永远不会发生。我们希望提供一些输入，例如从数据库获取的用户 ID、请求的 URL 或部分 URL，例如，仅地址组件。

为了做到这一点，我们必须创建一个函数。在本例中，我们将创建一个变量，它将是一个名为`asyncAdd`的函数：

```
var asyncAdd = () => {

}
```

这将是一个使用`setTimeout`模拟异步功能的函数。实际上，它只是将两个数字相加。然而，在本章后面，它将确切地说明我们需要做些什么，才能让我们的天气应用程序使用 promises。

现在在函数中，我们将接受两个参数，`a`和`b`，我们将返回一个承诺：

```
var asyncAdd = (a, b) => {

};
```

所以，无论谁调用这个`asyncAdd`方法，他们都可以传递输入，但他们也可以得到承诺，这样他们就可以使用它来同步并等待它完成。在`asyncAdd`函数中，我们将使用`return`来完成此操作。我们将使用与创建`somePromise`变量时完全相同的`new Promise`语法来`return`这个`new Promise`对象。现在这是同一个函数，所以我们确实需要提供使用`resolve`和`reject`调用的构造函数，如下所示：

```
var asyncAdd = (a, b) => {
 return new Promise((resolve, reject) => {

 });
```

现在我们有一个`asyncAdd`函数，它接受两个数字并返回一个承诺。剩下要做的唯一一件事就是实际模拟延迟，并调用`resolve`。为此，我们将使用`setTimeout`模拟延迟。然后我们将传入我的`callback`函数，将延迟设置为 1.5 秒或`1500`毫秒：

```
return new Promise((resolve, reject) => {
 setTimeout(() => {

 }, 1500)
 });
```

在`callback`函数中，我们将编写一个简单的`if-else`语句，检查`a`和`b`的类型是否都是数字。如果是，那太好了！我们将`resolve`两个数字相加的值。如果它们不是数字（一个或多个），那么我们将`reject`。为此，我们将使用`if`语句和`typeof`操作符：

```
setTimeout(() => {
  if (typeof a === 'number')
 }, 1500);
```

在这里，我们使用`typeof`对象获取变量前面的字符串类型。此外，我们正在检查它是否等于一个数字，这是当我们有一个数字时从`typeof`返回的结果。现在类似于`a`，我们将添加`typeof b`，这也是一个数字：

```
    if (typeof a === 'number' && typeof b === 'number') {}
```

我们可以将这两个数字相加，求出值。在`if`语句的代码块内，我们将调用`resolve`，传入`a + b`：

```
 return new Promise((resolve, reject) => {
   setTimeout(() => {
     if (typeof a === 'number' && typeof b === 'number') { 
       resolve(a + b);
     }
   }, 1500);
```

这将两个数字相加，将一个参数传递给`resolve`。当`a`和`b`都是数字时，这就是快乐之路。如果事情进展不顺利，我们将添加`reject`。我们将使用`else`块来执行此操作。如果前面的条件失败，我们将通过调用`reject('Arguments must be numbers')`来`reject`：

```
   if (typeof a === 'number' && typeof b === 'number') { 
     resolve(a + b);
   } else {
     reject('Argumets must be numbers');
   }
```

现在我们有一个`asyncAdd`函数，它接受两个变量`a`和`b`，返回一个承诺，任何碰巧调用`asyncAdd`的人都可以在返回结果上添加一个 then 调用以获得该值。

# 回报承诺

这到底是什么样子？为了说明这一点，首先我们将注释掉`promise.js`的`newPromise`变量中的所有代码。接下来，我们将调用`asyncAdd`变量，我们在其中生成`asyncAdd`。我们将通过传入两个值来调用它，就像调用任何其他函数一样。请记住，对于异步函数，这可能是一个数据库 ID 或其他任何内容。在我们的例子中，它只是两个数字。比如说，`5`和`7`。现在这个函数的返回值是一个承诺。我们可以创建一个变量，然后调用该变量，但我们也可以只使用`then`方法，如下所示：

```
asyncAdd(5, 7).then
```

这正是我们使用承诺时要做的；然后我们继续，把我们的回电传过来。第一个回调是成功案例，第二个回调是错误案例：

```
ouldasyncAdd(5, 7).then(() => {
}, () => {

});
```

在第二次回调中，我们将得到我们的`errorMessage`，我们可以使用`console.log(errorMessage);`语句将其登录到屏幕，如下所示：

```
asyncAdd(5, 7).then(() => {

}, (errorMessage) => {
 console.log(errorMessage);
});
```

如果一个或多个数字实际上不是数字，`error`函数将启动，因为我们调用了`reject`。如果两者都是数字，我们所要做的就是得到结果并使用`console.log`将其打印到屏幕上。我们将添加`res`，在 arrow 函数（`=>`中，我们将添加`console.log`语句，并用冒号打印字符串`Result`。然后，作为`console.log`中的第二个参数，我们将传入实际数字，并将其打印到屏幕上：

```
asyncAdd(5, 7).then(() => {
 console.log('Result:', res);
}, (errorMessage) => {
 console.log(errorMessage);
});
```

既然我们有了承诺的`asyncAdd`功能，让我们在终端内部进行测试。为此，我们将运行`nodemon`启动`nodemon playground/promise.js`：

![](assets/2c8c4cc6-4777-4da8-89e2-6f18d6255ec9.png)

马上，我们将得到延迟和结果，`12`打印到屏幕上。这太棒了！我们能够创建接受动态输入的函数，但仍然返回承诺。

现在请注意，我们使用了一个通常需要回调的异步函数，并将其包装为使用承诺。这是一个很好的便捷功能。当您开始在 Node 中使用承诺时，您会意识到有些东西不支持承诺，您希望它们支持承诺。例如，我们用来发出 HTTP 请求的请求库不支持本机承诺。但是，我们可以将请求调用封装在承诺中，这是我们将在本节后面要做的。现在，我们有一个基本的例子来说明这是如何工作的。接下来，我们想谈谈承诺链。

# 承诺链

承诺链是让多个承诺按顺序运行的想法。例如，我想把一个地址转换成坐标，把这些坐标转换成天气信息；这是一个需要同步两件事情的例子。此外，我们可以使用承诺链接轻松地实现这一点。

为了实现我们的承诺，在我们的成功电话中，我们将回报一个新的承诺。在我们的例子中，我们可以通过再次调用`asyncAdd`来`return`一个新的承诺。我将调用`res`和`console.log`语句旁边的`asyncAdd`，传递两个参数：结果、先前承诺返回的结果以及某种新的数字；让我们使用`33`：

```
asyncAdd(5, 7).then((res) => {
 console.log('Result:', res);
 return asyncAdd(res, 33);
```

现在我们返回一个承诺，这样我们就可以通过再次调用`then`方法来添加我的链接。在我们关闭上一个`then`方法的右括号后，`then`方法将被调用。这也需要一个或多个参数。我们可以传入一个成功处理程序，它是一个函数，一个错误处理程序，它也是一个函数：

```
 asyncAdd(5, 7).then((res) => {
   console.log('Result:', res);
   return asyncAdd(res, 33);
 }, (errorMessage) => {
   console.log(errorMessage);
 }).then(() => {

 }, () => {

 })
```

现在我们已经设置了`then`回调，我们可以实际填写它们了。我们将再次获得结果；这将是`5`加`7`的结果，即`12`，再加`33`，即`45`。然后，我们可以打印`console.log ('Should be 45')`。接下来，我们将打印 results 变量的实际值：

```
}).then((res) => {
 console.log('Should be 45', res);
}, () => {
});
```

现在，我们的错误处理程序也将是相同的。我们将有`errorMessage`并使用`console.log`打印`errorMessage`将其打印到屏幕上：

```
}).then((res) => {
 console.log('Should be 45', res);
}, (errorMessage) => {
 console.log(errorMessage);
});
```

现在我们有一些链子。我们的第一个 then`callback`函数将根据第一个`asyncAdd`调用的结果启动。如果进展顺利，第一个会开火。如果运行不好，第二个函数将启动。我们的第二个 then 呼叫将基于`asyncAdd`呼叫，其中我们添加了`33`。这将使我们将两个结果链接在一起，我们应该将`45`打印到屏幕上。我们将重新启动这个文件。最终，我们将得到两个结果：`12`和`Should be 45`。如下面的代码图所示，我们得到的只是，`Result: 12`和`Should be 45`打印到屏幕上：

![](assets/51085c19-914c-45d4-9900-831e8209b8ea.png)

# 承诺链中的错误处理

现在，当涉及到错误处理时，有一些怪癖；因此，我们将模拟一些错误。首先，让我们在第二次`asyncAdd`调用中模拟一个错误。我们知道我们可以通过传递一个不是数字的值来实现这一点。在本例中，让我们将`33`括在引号内：

```
 asyncAdd(5, 7).then((res) => {
   console.log('Result:', res);
   return asyncAdd(res, '33');
 }, (errorMessage) => {
   console.log(errorMessage);
 }).then((res) => {
   console.log('Should be 45', res);
 }, (errorMessage) => {
   concole.log(errorMessage);
 })
```

这将是一个字符串，我们的调用应为`reject`。现在，我们可以保存文件并查看发生了什么：

![](assets/07962445-c8f8-4784-8512-560de7bf4cec.png)

我们得到`Result: 12`，然后我们得到我们的错误`Arguments must be numbers`。正如我们所期望的，这是在屏幕上打印的。我们没有得到`Should be 45`，而是得到了错误消息。

但当承诺链中较早的东西被拒绝时，事情就变得有点棘手了。让我们用数字`33`交换`'33'`。然后用字符串`'7'`替换`7`，如下图：

```
 asyncAdd(5, '7').then((res) => {
   console.log('Result:', res);
   return asyncAdd(res, 33);
 }, (errorMessage) => {
   console.log(errorMessage);
 }).then((res) => {
   console.log('Should be 45', res);
 }, (errorMessage) => {
   concole.log(errorMessage);
 })
```

这将导致我们的第一个承诺失败，这意味着我们永远看不到结果。我们应该看到错误消息打印到屏幕上，但不会发生这种情况：

![](assets/9144348b-9213-4f2b-89ff-9d3a09e6dff6.png)

当我们重新启动时，确实会将错误消息打印到屏幕上，但是我们也会得到`Should be 45 undefined`。第二个`console.log`正在运行，因为我们在第二个`asyncAdd`函数中提供了一个错误处理程序。它正在运行错误处理程序。然后它说，*好了，现在我们运行了错误处理程序，情况一定很好。让我们继续下一步，然后调用成功案例*。

# 捕捉法

要修复错误，我们可以从两个`then`调用中删除两个错误处理程序，并在最底层用另一个调用替换它们，然后调用另一个方法`.catch`：

```
asyncAdd(5, '7').then((res) => {
 console.log('Result:', res);
 return asyncAdd(res, 33);
}).then((res) => {
 console.log('Should be 45', res);
}).catch;
```

catch-promise 方法与 then 类似，但它只需要一个函数。这是错误处理程序。如下面的代码所示，如果任何 promise 调用失败，我们可以指定一个错误处理程序。我们将采用`errorMessage`并使用`console.log(errorMessage)`将其打印到屏幕上：

```
asyncAdd(5, '7').then((res) => {
 console.log('Result:', res);
 return asyncAdd(res, 33);
}).then((res) => {
 console.log('Should be 45', res);
}).catch((errorMessage) => {
 console.log(errorMessage)
});
```

不过现在，如果事情有点模糊，那没关系，只要你开始准确地看到我们在做什么。我们从一个承诺中获得结果，并将其传递给另一个承诺。在这种情况下，结果完全符合预期。第一个承诺失败了，我们得到，`Arguments must be numbers`在屏幕上打印。另外，我们在打印`45`时并没有得到错误的语句，而是得到了未定义的语句。使用 catch，我们可以指定一个错误处理程序，它将为我们以前的所有失败触发。这正是我们想要的。

# promises 中的请求库

正如我前面提到的，一些库支持承诺，而另一些库则不支持。请求库不支持承诺。我们将创建一个函数来包装请求，返回一个承诺。我们将使用上一章中`geocode.js`文件中的一些功能。

首先，让我们讨论一个快速设置，然后我们将实际填写它。在`playground`文件夹中，我们可以创建一个新文件来存储该文件，称为`promise-2.js`：

![](assets/e237b240-cc2b-44e0-887a-52ae3eba14e2.png)

我们将创建一个名为`geocodeAddress`的函数。`geocodeAddress`函数将采用纯文本地址，并返回一个承诺：

```
var geocodeAddress = (address) => {

};
```

`geocodeAddress`函数将返回一个承诺。因此，如果我传入一个邮政编码，比如`19146`，我会期望得到一个承诺，我可以附加一个`then`电话。这将让我等待该请求完成。在这里，我将附加对`then`的调用，传入我的两个函数：承诺履行时的成功处理程序和承诺拒绝时的错误处理程序：

```
geocodeAddress('19146').then(() => {

}, () => {

})
```

现在，当事情进展顺利时，我会期待带有地址的`location`对象、`latitude`和`longitude`，当事情进展不顺利时，我会期待错误消息：

```
geocodeAddress('19146').then((location) => {

}, (errorMessage) => {

})
```

当错误消息发生时，我们将使用`console.log (errorMessage)`将其打印到屏幕上。现在，当事情进展顺利并且成功案例运行时，我们将使用漂亮的打印技术`console.log`打印整个对象。然后，我们将调用`JSON.stringify`，就像我们以前多次做的那样，传入三个参数对象，未定义为我们在书中永远不会使用的过滤方法，以及数字`2`，表示我们希望用作缩进的空格数：

```
geocodeAddress('19146').then((location) => {
 console.log(JSON.stringify(location, undefined, 2));
}, (errorMessage) => {
 console.log(errorMessage); 
});
```

这就是我们想要创建的功能，使此功能按预期工作。这个`then`调用应该如前面的代码所示工作。

为了开始，我将通过调用：`return new Promise`，传入我的构造函数来返回承诺：

```
var geocodeAddress = (address) => {
 return new Promise(() => {

 });
};
```

在函数内部，我们将该调用添加到请求中。让我们提供`resolve`和`reject`参数：

```
 return new Promise((resolve, reject) => {
 });
};
```

现在我们已经设置了`Promise`，我们可以在代码顶部加载请求模块，创建一个名为`request`的常量，并将其设置为等于`require('request')`的返回结果：

```
const request = require('request');

var geocodeAddress = (address) => {
```

接下来，我们将移动到`geocode.js`文件中，获取`geocodeAddress`函数中的代码，并将其移动到`promise-2 file`中，构造函数中：

```
const request = require('request');
var geocodeAddress = (address) => {
 return new Promise((resolve, reject) => {
 var encodedAddress = encodeURIComponent(address);

request({
 url: `https://maps.googleapis.com/maps/api/geocode/json?address=${encodedAddress}`,
 json: true
 }, (error, response, body) => {
   if (error) {
   callback('Unable to connect to Google servers.');
 } else if (body.status === 'ZERO_RESULTS') {
   callback('Unable to find that address.');
 } else if (body.status === 'OK') {
   callback(undefined, {
     address: body.results[0].formatted_address,
     latitude: body.results[0].geometry.location.lat,
     longitude: body.results[0].geometry.location.lng
     });
    }
   });
 });
};
```

现在我们基本上可以走了；我们只需要改变一些事情。我们需要做的第一件事是替换错误处理程序。在代码的`if`块中，我们用一个参数调用了`callback`处理程序；相反，我们将调用`reject`，因为如果此代码运行，我们希望`reject`承诺。我们在下一个`else`街区有同样的东西。如果我们得到`ZERO_RESULTS`，我们会打电话`reject`。这确实是一次失败，我们不想假装我们成功了：

```
if (error) {
   reject('Unable to connect to Google servers.');
 } else if (body.status === 'ZERO_RESULTS') {
   reject('Unable to find that address.');
```

现在在下一个`else`街区，事情进展顺利；这里我们可以叫`resolve`。此外，我们可以删除第一个参数，因为我们知道`resolve`和`reject`只接受一个参数：

```
if (error) { 
  reject('Unable to connect to Google servers.');
 } else if (body.status === 'ZERO_RESULTS') {
   reject('Unable to find that address.');
 } else if (body.status === 'OK') {
   resolve(
```

我们可以指定多个值，因为我们`resolve`是一个具有属性的对象。既然我们已经准备好了，我们就完成了。我们实际上可以保存我们的文件，在终端内部重新运行它，并进行测试。

# 测试请求库

为了测试，我们将保存文件，移动到终端，并关闭`promise.js`文件的`nodemon`。我们将运行`node`获取`promise.js`文件。在`playground`文件夹中，名为`promise-2.js`：

```
node playground/promise-2.js
```

现在，当我们运行这个程序时，我们实际上是在发出 HTTP 请求。如以下代码输出所示，我们可以看到数据完全按照预期返回：

![](assets/1fa26c34-7594-4433-ac64-700af003a6eb.png)

我们得到了`address`、`latitude`和`longitude`变量。这太棒了！现在让我们测试一下当我们传入一个无效地址时会发生什么，比如 5 个零，我们以前用过它来模拟一个错误：

```
const request = require('request');

var geocodeAddress = (address) => {
  return new Promise((resolve, reject) => {
    var encodedAddress = encodeURIComponent(address);

  request({
   url: `https://maps.googleapis.com/maps/api/geocode/json?address=${encodedAddress}`,
   json: true
 }, (error, response, body) => {
   if (error) {
     reject('Unable to connect to Google servers.');
   } else if (body.status === 'ZERO_RESULTS') {
     reject('Unable to find that address.');
   } else if (body.status === 'OK') {
     resolve({
       address: body.results[0].formatted_address,
       latitude: body.results[0].geometry.location.lat,
       longitude: body.results[0].geometry.location.lng
      });
     }
   });
  });
};
```

我们将保存文件，重新运行程序，`Unable to find that address.`将打印到屏幕上：

![](assets/dd136fb7-56f6-4180-8d82-fb50a1c5e611.png)

这只是因为我们称之为`reject`。我们将在`Promise`构造函数内部调用`reject`。我们有错误处理程序，它将消息打印到屏幕上。这是一个如何获取不支持承诺的库并将其包装为承诺的示例，从而创建一个支持承诺的函数。在我们的例子中，该函数是`geocodeAddress`。

# 承诺天气应用程序

在本节中，我们将学习如何使用内置承诺的库。我们将探索 axios 库，它与请求非常相似。尽管如此，它并没有像请求那样使用回调，而是使用承诺。因此，我们不必用承诺来包装我们的通话，以获得承诺功能。我们将在本节中重新创建整个天气应用程序。我们只需要写大约 25 行代码。我们将经历整个过程：获取地址、坐标，然后获取天气。

# 从 app.js 文件获取天气应用程序代码

为了从 app.js 文件中获取天气应用程序代码，我们将复制`app.js`，因为我们在原始`app.js`文件中配置了`yargs`，并且我们希望将代码带到新项目中。没有必要重写它。在`weather`目录中，我们将复制`app.js`，给它一个新名称`app-promise.js`。

在`app-promise.js`里面，在我们添加任何东西之前，让我们先把一些东西撕下来。我们将删除`geocode`和`weather`变量声明。我们不需要任何文件：

![](assets/d3bb21f5-b5b1-4c6a-a140-4ff58de97564.png)

然后我将在我们的`yargs`配置之后删除所有内容，在本例中，这只是我们对`geocodeAddress`的调用。生成的代码如下所示：

```
const yargs = require('yargs');

const argv = yargs
 .options({
   a: {
     demand: true,
     alias: 'address',
     describe: 'Address to fetch weather for',
     string: true
   }
 })
 .help()
 .alias('help', 'h')
 .argv;
```

# Axios 文档

现在我们已经有了一个新的记录，我们可以开始安装新的库了。在运行`npm install`命令之前，我们将查看在哪里可以找到文档。我们可以访问：[获取 https://www.npmjs.com/package/axios](https://www.npmjs.com/package/axios) 。如以下屏幕截图所示，我们有 axios npm library 页面，可以在其中查看有关它的各种信息，包括文档：

![](assets/a1b15161-a362-4fa5-a931-7c7d8f79ad9f.png)

在这里我们可以看到一些看起来很熟悉的东西。我们有电话去接，就像我们在 axios 之外使用承诺一样：

![](assets/c120402b-5698-4ec0-8c0a-7b838ad882ac.png)

在这个页面的 stats 列中，您可以看到这是一个超级流行的库。最新版本是 0.13.1。这正是我们将要使用的版本。在项目中使用 axios 时，请随时转到本页。有很多非常好的例子和文档。但是现在，我们可以安装它。

# 安装 axios

要安装 axios，在终端内部，我们将运行`npm install`；库名为`axios`，我们将使用`save`标志指定版本`0.17.1`更新`package.json`文件。现在我可以运行`install`命令来安装 axios：

![](assets/7b94abf0-4c96-4509-b51d-4076e50445e2.png)

# 在应用承诺文件中拨打电话

在我们的`app-promise`文件中，我们可以开始加载顶部的`axios`。我们将创建一个名为`axios`的常数，将其设置为`require('axios')`，如下所示：

```
const yargs = require('yargs');
const axios = require('axios');
```

现在我们已经准备好了，我们可以开始在代码中进行调用了。这将涉及我们从地理代码和天气文件中提取一些功能。所以我们将打开`geocode.js`和`weather.js`文件。因为我们将从这些文件中提取一些代码，比如 URL 和一些错误处理技术。尽管我们会在讨论差异时讨论它们。

我们需要做的第一件事是对地址进行编码并获取地理编码 URL。现在这些事情发生在`geocode.js`内部。因此，我们将实际复制`encodedAddress`变量行，在其中创建编码地址，并将其粘贴到`app-promise`文件中`argv`变量后面：

```
  .argv;

var encodedAddress = encodeURIComponent(argv.address);
```

现在我们需要稍微调整一下。`address`变量不存在；但是我们有`argv.address`。那么，我们将`address`切换为`argv.address`：

```
var encodeAddress = encodeURIComponent(argv.address);
```

现在我们有了编码地址；在开始使用 axios 之前，我们需要得到的下一件事是我们要向其发出请求的 URL。我们也将从`geocode.js`文件中获取。在`app-promise.js`中，我们将创建一个名为`geocodeURI`的新变量。然后取`geocode.js`中的 URL，从开始勾号到结束勾号，复制粘贴到`app-promise.js`中，等于`geocodeURI`：

```
var encodedAddress = encodeURIComponent(argv.address);
var geocodeUrl = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodedAddress}`;
```

现在我们在 URL 中使用编码的`address`变量；这很好，因为它确实存在于我们的代码中。现在，我们有了`geocodeUrl`变量，我们可以开始提出第一个 axios 请求。

# 发出 axios 请求

在我们的例子中，我们将获取地址并获得`latitude`和`longitude`。要发出请求，我们将调用 axios 上可用的方法，`axios.get`：

```
var geocodeUrl = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodedAddress}`;

axios.get
```

`get`是允许我们发出 HTTP get 请求的方法，这正是我们在本例中想要做的。而且，它的设置非常简单。当您需要 JSON 数据时，您所要做的就是传入`geocodeUrl`变量中的 URL。不需要提供任何其他选项，比如让它知道它`JSON. axios`知道如何自动解析 JSON 数据的选项。得到的回报实际上是一个承诺，这意味着我们可以使用`.then`在承诺得到履行或拒绝时运行一些代码，无论事情进展顺利还是糟糕：

```
axios.get(geocodeUrl).then()
```

在内部，我们将提供一个函数。这将是成功的案例。成功案例将通过一个参数调用，`axios`库建议您调用`response`：

```
axios.get(geocodeUrl).then((response) => {

});
```

从技术上讲，我们可以叫你喜欢的任何东西。现在，在函数中，我们将访问请求库中获得的所有相同信息；诸如我们的标题、响应和请求标题，以及主体信息；各种有用的信息。我们真正需要的是`response.data`财产。我们将使用`console.log`打印：

```
axios.get(geocodeUrl).then((response) => {
  console.log(response.data);
});
```

现在我们已经准备好了，我们可以运行我们的`app-promise`文件，传递一个有效的地址。此外，我们可以看到当我们提出请求时会发生什么。

在命令行（终端）中，我们将首先使用`clear`命令清除终端输出。然后我们可以运行`node``app-promise.js`，传递一个地址。让我们使用一个有效的地址，例如，`1301 lombard street, philadelphia`：

```
node app-promise.js -a '1301 lombard street philadelphia
```

请求发出了。我们还能得到什么？我们得到的结果对象与我们在前几章中使用其他模块时看到的完全相同：

![](assets/b9b590ca-3f30-4583-9aa6-d9bad585323b.png)

这种情况下唯一的区别是，我们使用内置的承诺，而不是用承诺或回调来包装它。

# axios 请求中的错误处理

现在，除了我们在前面的示例中使用的成功处理程序之外，我们还可以添加一个 catch 调用，以便捕获可能发生的所有错误。我们将获取 error 对象作为唯一的参数；然后我们可以对该错误对象执行一些操作：

```
axios.get(geocodeUrl).then((response) => {
 console.log(response.data);
});catch((e) => {

});
```

在函数内部，我们将开始使用`console.log`打印错误参数：

```
}).catch((e) => {
 console.log(e)
});
```

现在，让我们通过删除 URL 中的点来模拟一个错误：

```
var encodedAddress = encodeURIComponent(argv.address);
var geocodeUrl = `https://mapsgoogleapis.com/maps/api/geocode/json?address=${encodedAddress}`;

axios.get(geocodeUrl).then((response) => {
   console.log(response.data);
}).catch((e) => {
   console.log(e)
});
```

我们可以看到当我们重新运行程序时会发生什么。现在我这样做是为了探索`axios`图书馆。我确切地知道会发生什么。这不是我这么做的原因。我这样做是为了向你展示你应该如何接触新的图书馆。当你得到一个新的库时，你想玩弄它所有不同的工作方式。当我们有一个失败的请求时，错误参数中到底返回了什么？这是需要了解的重要信息；因此，在编写真实世界的应用程序时，可以添加适当的错误处理代码。

在这种情况下，如果我们重新运行完全相同的命令，我们将得到一个错误：

![](assets/8b892515-a390-41a9-84d2-56b558906ea9.png)

正如你所看到的，屏幕上真的没有什么可打印的东西。我们有很多非常隐秘的错误代码，甚至还有`errorMessage`属性，它通常包含好的或不好的内容。然后我们有一个错误代码，后跟 URL。我们想要的是打印一条纯文本英文消息。

为此，我们将使用一个`if-else`语句，检查代码属性是什么。这是错误代码，在本例中为`ENOTFOUND`；我们知道这意味着它无法连接到服务器。在`app-promise.js`中，在错误处理程序中，我们可以通过`if`并检查条件来添加：

```
}).catch((e) => {
 if (e.code === 'ENOTFOUND') {

}
```

如果是这种情况，我们将使用`console.log`在屏幕上打印某种自定义消息：

```
}).catch((e) => {
  if (e.code === 'ENOTFOUND') {
   console.log('Unable to connect to API servers.');
  } 
  console.log(e);
 });
```

现在我们有了一个错误处理程序来处理这个特定的情况。因此，我们可以取消对`console.log`的呼叫：

```
axios.get(geocodeUrl).then((response) => {
  console.log(response.data);
}).catch((e) => {
  if (e.code === 'ENOTFOUND') {
    console.log('Unable to connect to API servers.');
 }
});
```

现在，如果我们保存文件，并从终端重新运行，我们应该会得到一个更好的错误消息打印到屏幕上：

![](assets/53f9b560-267b-411e-a2d1-6615e4267ddf.png)

这正是我们得到的：`Unable to connect to API servers`。现在我要把那个点加进去，这样事情就可以开始了。我们可以担心会有什么反应。

# 零结果体状态的错误处理

正如您所记得的，在地理代码文件中，我们需要做一些事情。我们已经处理了与服务器连接相关的错误，但是还有另一个待处理的错误，即如果`body.status`属性等于`ZERO_RESULTS`。在这种情况下，我们希望打印一条错误消息。

为此，我们将在`app-promise`中创建我们自己的错误。我们将在`axios.get`函数中抛出一个错误。此错误将导致其后面的所有代码无法运行。它将直接移动到错误处理程序中。

现在我们只想在 status 属性设置为`ZERO_RESULTS`时抛出一个错误。我们将在`get`函数的最顶端添加一条`if`语句，以检查`if (response.data.status)`是否等于`ZERO_RESULTS`：

```
axios.get(geocodeUrl).then((response) => {
  if (response.data.status === 'ZERO_RESULTS') {

  }
```

如果是这样的话，那么事情就糟了，我们不想继续提出天气要求。我们想运行我们的捕获代码。要抛出承诺可能捕获的新错误，我们将使用名为`throw new Error`的语法。这将创建并抛出一个错误，让节点知道发生了错误。我们可以提供我们自己的错误消息，这是用户可读的：`Unable to find that address`：

```
axios.get(geocodeUrl).then((response) => {
  if (response.data.status === 'ZERO_RESULTS') {
    throw new Error('Unable to find that address.');
  }
```

这条消息会让用户确切地知道出了什么问题。现在，当抛出此错误时，将运行相同的 catch 代码。目前，我们只有一个`if`条件来检查代码属性是否为`ENOTFOUND`。因此，我们将添加一个`else`条款：

```
axios.get(geocodeUrl).then((response) => {
 if (response.data.status === 'ZERO_RESULTS') {
   throw new Error('Unable to find that address.');
 }

 console.log(response.data);
}).catch((e) => {
 if (e.code === 'ENOTFOUND') {
   console.log('Unable to connect to API servers.');
 } else {

 }
});
```

在`else`块中，我们可以打印错误消息，这是我们使用`e.`消息属性在抛出`new Error`语法中键入的字符串，如下所示：

```
axios.get(geocodeUrl).then((response) => {
 if (response.data.status === 'ZERO_RESULTS') {
   throw new Error('Unable to find that address.');
 }

 console.log(response.data);
}).catch((e) => {
  if (e.code === 'ENOTFOUND') {
   console.log('Unable to connect to API servers.');
 } else {
   console.log(e.message);
 }
});
```

如果错误代码不是`ENOTFOUND`，我们只需将消息打印到屏幕上即可。如果我们得到的结果为零，就会发生这种情况。让我们模拟一下，以确保代码正常工作。在终端内部，我们将重新运行上一个命令，并传入邮政编码。首先，我们将使用一个有效的邮政编码，`08822`，我们应该取回我们的数据。然后我们将使用一个无效的：`00000`。

当我们使用有效地址运行请求时，会得到以下结果：

![](assets/c125c1ba-ce47-4adb-9d2f-6f996c2bf381.png)

当我们使用无效地址运行请求时，会出现以下错误：

![](assets/3acd268c-c83b-486e-98a9-87c2e2ad37eb.png)

通过调用`throw new Error`，我们将立即停止此函数的执行。所以`console.log`和`e.message`从不打印，这正是我们想要的。现在我们已经准备好了错误处理程序，可以开始生成天气 URL 了。

# 生成天气 URL

为了生成天气 URL，我们将复制`weather`文件中的 URL，并将其与记号一起放入`app-promise`文件中。我们将创建一个名为`weatherUrl`的新变量，将其设置为与复制的 URL 相等：

```
url: `https://api.forecast.io/forecast/4a04d1c42fd9d32c97a2c291a32d5e2d/${lat},${lng}`,
```

现在`weatherUrl`确实需要一些信息。我们需要`latitude`和`longitude`。我们有两个变量`lat`和`lng`，所以让我们创建它们，从响应对象`var lat`和`var lng`中获取适当的值：

```
var lat;
var lng;
url: `https://api.forecast.io/forecast/4a04d1c42fd9d32c97a2c291a32d5e2d/${lat},${lng}`,
```

现在，为了把它们拉下来，我们必须经历挖掘物体的过程。我们以前做过。我们将在响应对象中查看 data 属性，它类似于请求库中的主体。然后进入`results`，抓取第一项，访问`geometry`属性，然后访问`location.lat`：

```
var lat = response.data.results[0].geometry.location.lat;
```

同样地，我们可以为`longitude`变量添加内容：

```
var lat = response.data.results[0].geometry.location.lat;
var lng = response.data.results[0].geometry.location.lng;
```

现在，在我们发出天气请求之前，我们要打印格式化的地址，因为这也是以前的应用程序所做的。在我们的`console.log(response.data)`语句中，我们将深入获取格式化地址的数据对象，而不是打印`response.data`。这也是结果数组的第一项。我们将访问`formatted_address`属性：

```
var lat = response.data.results[0].geometry.location.lat;
var lng = response.data.results[0].geometry.location.lng;
var weatherUrl = `https://api.forecast.io/forecast/4a04d1c42fd9d32c97a2c291a32d5e2d/${lat},${lng}`;
console.log(response.data.results[0].formatted_address);
```

现在我们已经将格式化的地址打印到屏幕上，我们可以通过返回新的承诺来进行第二次呼叫。这将让我们把这些电话连在一起。

# 把承诺挂在电话上

首先，我们将返回一个调用`axios.get`，并传入 URL。我们刚才定义的是`weatherUrl`：

```
 var lat = response.data.results[0].geometry.location.lat;
 var lng = response.data.results[0].geometry.location.lng;
 var weatherUrl = `https://api.forecast.io/forecast/4a04d1c42fd9d32c97a2c291a32d5e2d/${lat},${lng}`;
 console.log(response.data.results[0].formatted_address);
 return axios.get(weatherUrl);
```

现在我们有了这个调用返回，我们可以在前面的`then`调用和 catch 调用之间附加另一个`then`调用，然后调用，传入一个函数，如下所示：

```
 return axios.get(weatherUrl);
}).then(() => {

}).catch((e) => {
 if (e.code === 'ENOTFOUND') {
```

当天气数据返回时，将调用此函数。我们将得到相同的响应参数，因为我们使用相同的方法，`axios.get`：

```
}).then((response) => {
```

在`then`调用中，我们不必担心抛出任何错误，因为我们从不需要访问 body 属性来检查是否出现错误。对于天气请求，如果这个回调运行，那么事情就正常了。我们可以打印天气信息。为了实现这一点，我们将创建两个变量：

*   `temperature`
*   `apparentTemperature`

`temperature`变量将被设置为等于`response.data`。然后我们将访问该`currently`属性。然后我们将获得温度。我们将拉出第二个变量，实际温度或`apparentTemperature`，这是属性名称`var apparentTemperature`。我们将其设置为`response.data.currently.apparentTemperature`：

```
}).then((response) => {
 var temperature = response.data.currently.temperature;
 var apparentTemperature = response.data.currently.apparentTemperature;
```

现在我们已经将两个东西提取到变量中，我们可以在调用`console.log`中添加这些东西。我们选择定义两个变量，这样就不必将两个非常长的属性语句添加到`console.log`。我们可以简单地引用变量。我们将添加`console.log`并在`console.log`语句中使用模板字符串，以便我们可以在引号中插入前面提到的两个值：`It's currently`，然后是`temperature`。然后我们可以添加一个句点，`It feels like`，后跟`apparentTemperature`：

```
}).then((response) => {
 var temperature = response.data.currently.temperature;
 var apparentTemperature = response.data.currently.apparentTemperature;
 console.log(`It's currently ${temperature}. It feels like ${apparentTemperature}.`);
```

现在我们已经将字符串打印到屏幕上，我们可以测试我们的应用程序是否按预期工作。我们将保存该文件，并在终端内部重新运行两个命令之前的命令，其中包含有效的邮政编码：

![](assets/45cf383a-3a5f-4c59-a096-2ba3d38088a0.png)

当我们运行此程序时，我们将获得新泽西州`Flemington`的天气信息。现在是`84`度，但感觉像`90`。如果我们运行了地址不正确的程序，我们会收到错误消息：

![](assets/3b8c8c29-25de-44af-8688-7ebd557f4cc8.png)

所以一切看起来都很棒！使用`axios`库，我们可以像应用程序 promise 一样链接承诺，而无需做任何太疯狂的事情。`axios get`方法返回一个承诺，因此我们可以使用 then 直接访问它。

在代码中，我们使用 then once 对地理位置数据进行处理。我们把地址打印到屏幕上。然后，我们回报另一个承诺，在那里我们提出了天气的要求。在第二次`then`通话中，我们将天气打印到屏幕上。我们还添加了一个 catch 调用，它将处理任何错误。如果我们的承诺出现任何问题，或者我们抛出了错误，catch 将被解雇，并将消息打印到屏幕上。

这就是使用 axios 并为 HTTP 请求设定承诺所需的全部内容。现在，人们喜欢承诺而不是传统回调的一个原因是，我们可以简单地链接，而不是嵌套。所以我们的代码不会缩进到疯狂的程度。正如我们在上一章的`app.js`中所看到的，我们深入了几个缩进级别，只是为了将两个调用添加到一起。如果我们需要增加第三个，情况会变得更糟。有了承诺，我们可以将所有内容保持在同一水平，使代码更易于维护。

# 总结

在本章中，我们通过简单介绍基本原理，快速介绍了承诺是如何起作用的。异步是 Node.js 的关键部分。我们经历了最基本的回访和承诺。我们看了几个例子，创建了一个非常酷的天气应用程序。

这就结束了异步 Node.js 编程，但这并不意味着您必须停止构建天气应用程序。关于你可以做些什么来继续这个项目，有一些想法。首先，您可以加载更多信息。我们从天气 API 中得到的响应除了当前的温度（我们使用的温度）之外，还包含了很多东西。如果你能在那里加入一些东西，无论是高温/低温，还是降水的可能性，那就太好了。

接下来，拥有一个默认的定位能力会很酷。将有一个命令，让我设置一个默认位置，然后我可以运行没有位置参数的天气应用程序来使用该默认值。我们总是可以指定一个位置参数来搜索其他地方的天气。这将是一个非常棒的特性，它的工作原理类似于 Notes 应用程序，我们将数据保存到文件系统中。

在下一章中，我们将开始创建异步的 web 服务器。我们将制作异步的 API。此外，我们还将创建实时 Socket.IO 应用程序，它将是异步的。我们将继续创建部署到服务器上的节点应用程序，使任何具有 web 连接的人都可以访问这些服务器。